version: '3'

services:
  db:
    build: .
    image: test/postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    tty: true

  outerdb:
    image: test/postgres:latest
    container_name: outerdb
    tty: true

